version: "3.9"

services:
  web:
    build: .
    ports:
      - 3001:3000
    environment:
      - DB_HOST=mariadb
      - DB_USER=luis
      - DB_PASSWORD=MuchoTexto2023
      - DB_PORT=3306
      - DB_DATABASE=agencia_autos
      - PORT=3000
    links:
      - mariadb
    volumes:
      - .:/app
  mariadb:
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MARIADB_USER=luis
      - MARIADB_PASSWORD=MuchoTexto2023
      - MARIADB_DATABASE=agencia_autos
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./src/config/db.sql:/docker-entrypoint-initdb.d/db.sql
